### ISSUE TITLE
丢失数据问题

### ISSUE THREAD

**Issue by zzzzzhangyanqiu** [bbossgroups/kafka2x-elasticsearch#1]
您好，我在使用该框架同步kafka数据的时候，总会遇到数据丢失的问题（如1W条数据，只插入了8000条或者7000条），猜测是否是因为多线程导致的线程不安全，使用的代码是Kafka2ESdemo.java，没有做配置方面的修改，期待得到您的回复

**Comment by yin-bp** [comment]
Hi,@suiyueranzly,可以参考一下以下文档：
[数据导入不完整原因分析及处理](https://esdoc.bbossgroups.com/#/db-es-tool?id=_249-%e6%95%b0%e6%8d%ae%e5%af%bc%e5%85%a5%e4%b8%8d%e5%ae%8c%e6%95%b4%e5%8e%9f%e5%9b%a0%e5%88%86%e6%9e%90%e5%8f%8a%e5%a4%84%e7%90%86)
